services:
  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3005:3000

  frontend-post:
    build:
      context: ./frontend/post
      dockerfile: ./Dockerfile
    ports:
      - 3003:3003
    depends_on:
      backend:
        condition: service_started

  frontend-profile:
    build:
      context: ./frontend/profile
      dockerfile: ./Dockerfile
    ports:
      - 3002:3002
    depends_on:
      backend:
        condition: service_started

  frontend-auth:
    build:
      context: ./frontend/auth
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    depends_on:
      backend:
        condition: service_started

  frontend-mesto:
    build:
      context: ./frontend/mesto
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_started
      frontend-auth:
        condition: service_started
      frontend-post:
        condition: service_started
      frontend-profile:
        condition: service_started
